#!/usr/bin/env bash

command_exists() {
  type "$1" >/dev/null 2>&1
}

_colorized () {
  local color = $1
  local content = $2
  echo "\e[$color]${content}\e[m"
}

_w () {
  echo "$(_colorized 0;31 "DOTLYX:") $0"
}

if ! command_exists curl; then
  _w "curl not installed, trying to install"

  if command_exists apt; then
    _w "Installing using apt"
    _w "Installing curl"
    sudo apt -y install curl 2>&1
  elif command_exists dnf; then
    _w "Installing using dnf"
    _w "Installing curl"
    sudo dnf -y install curl 2>&1
  elif command_exists yum; then
    _w "Installing using yum"
    _w "Installing curl"
    yes | sudo yum install curl 2>&1 
  elif command_exists brew; then
    _w "Installing using brew"
    _w "Installing curl"
    yes | brew install curl 2>&1 
  elif command_exists pacman; then
    _w "Installing using pacman"
    _w "Installing curl"
    sudo pacman -S --noconfirm curl 2>&1 
  else
    _w "Could not install curl, no package provider found"
    exit 1
  fi
fi

if ! command_exists git; then
  _w "git not installed, trying to install"

  if command_exists apt; then
    _w "Installing using apt"
    _w "Installing git"
    sudo apt -y install git 2>&1
  elif command_exists dnf; then
    _w "Installing using dnf"
    _w "Installing git"
    sudo dnf -y install git 2>&1
  elif command_exists yum; then
    _w "Installing using yum"
    _w "Installing git";
    yes | sudo yum install git 2>&1 
  elif command_exists brew; then
    _w "Installing using brew"
    _w "Installing git"
    yes | brew install git 2>&1 
  elif command_exists pacman; then
    _w "Installing using pacman"
    _w "Installing git"
    sudo pacman -S --noconfirm git 2>&1 
  else
    _w "Could not install git, no package provider found"
    exit 1
  fi
fi

if ! command_exists python3; then
  _w "python not installed, trying to install"

  if command_exists apt; then
    _w "Installing using apt"
    _w "Installing python"
    sudo apt -y install python3 2>&1
  elif command_exists dnf; then
    _w "Installing using dnf"
    _w "Installing python"
    sudo dnf -y install python3 2>&1
  elif command_exists yum; then
    _w "Installing using yum"
    _w "Installing python";
    yes | sudo yum install python3 2>&1 
  elif command_exists brew; then
    _w "Installing using brew"
    _w "Installing python"
    yes | brew install python3 2>&1 
  elif command_exists pacman; then
    _w "Installing using pacman"
    _w "Installing python"
    sudo pacman -S --noconfirm python3 2>&1 
  else
    _w "Could not install python, no package provider found"
    exit 1
  fi
fi

if ! command_exists nix; then
  _w "nix is not installed, trying to install"
  SYSTEMD_ENABLED=1;

  check_systemd() {
      if command -v systemctl >/dev/null 2>&1; then
          $SYSTEMD_ENABLED=0
      fi
      if [ "$(ps -p 1 -o comm=)" = "systemd" ]; then
          $SYSTEMD_ENABLED=0
      fi
      if [ -d /lib/systemd ] || [ -d /usr/lib/systemd ]; then
          $SYSTEMD_ENABLED=0
      fi
  }

  if [ $SYSTEMD_ENABLED -eq 0 ]; then
      echo "Enabling systemd-dependent features..."
      curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s \
        -- install \
        --no-confirm
  else
      echo "Using alternative to systemd..."
      curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s \
        -- install linux \
        --init none \
        --no-confirm
  fi
  . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
fi

sudo rm -rf $HOME/dotlyx
git clone https://github.com/goi17/dotlyx.git $HOME/dotlyx
cd $HOME/dotlyx
nix build --file core/setup/install.nix -- --show-trace
./result/bin/dotlyx-setup $@
