#!/usr/bin/env bash
set -euo pipefail

if ! curl -fsSL https://raw.githubusercontent.com/GOI17/dotlyx/HEAD/requirements | bash; then
  echo "❌ Requirements check failed. Aborting installation." >&2
  exit 1
fi

sudo rm -rf "$HOME/dotlyx"

if ! git clone https://github.com/goi17/dotlyx.git "$HOME/dotlyx"; then
  echo "❌ Failed to clone repository." >&2
  exit 1
fi

cd "$HOME/dotlyx"

TARGET_PATH="/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh"

if [ -e "$TARGET_PATH" ]; then
    echo "Nix path exists: '$TARGET_PATH'"
    . "$TARGET_PATH"
else
    echo "Nix path does not exist: '$TARGET_PATH'" >&2
    exit 1
fi

if ! nix build --extra-experimental-features "nix-command flakes" --file core/setup/install.nix; then
  echo "❌ Nix build failed." >&2
  exit 1
fi

./result/bin/dotlyx-setup "$@"
