#!/usr/bin/env bash
set -e

VERSION=$1
if [ -z "$VERSION" ]; then
  read -p "Enter new version (without v prefix): " VERSION
fi

git tag -a "v$VERSION" -m "Release v$VERSION"
git push origin "v$VERSION"
sed -i -e "s|XXX_DOTLYX_RELEASE_XXX|''$VERSION|g" ./core/setup/install.nix
echo "Tag v$VERSION created and pushed. Derivation updated."
