#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"
source "$DOTFILES_PATH/scripts/tmux/utils/sessions.sh"

##? Pick and kill tmux session
#?? 0.0.1
##?
##? Usage:
##?    session-kill
docs::parse "$@"

tmux kill-session -t "$(get_tmux_sessions)"
