{
  "com.apple.madrid" = {
    AttachmentFileSizeUpdateWatermark = 0;
    AttachmentReuploadDate = "2024-12-12 06:23:30";
    CKMOCAccountsMatch = true;
    CloudKitCheckedMiCSwitchEligibilityOnImagentLaunch = true;
    CloudKitEligibleToToggleMiCSwitch = true;
    CloudKitHasAvailableRecordsToDownload = true;
    CloudKitIsEligibleForTruthZone = true;
    CloudKitIsRemovedFromBackup = false;
    CloudKitIsSyncing = false;
    CloudKitLastDownloadProgress = 1.0;
    CloudKitSyncDate = "2024-12-19 02:12:03";
    CloudKitSyncingEnabled = true;
    CloudKitTelemetrySyncVersion = 1;
    CloudKitVerifyFirstRestoreDateVersion = 1;
    DonatedRecentLiteHandles = 2;
    DonatedRecentLiteHandlesFromDevice = "CEDCED0C-685B-4E5E-9E3E-622582CAB8A0";
    IMCKRampState = { FeaturePromoted = false; FetchHadServerError = false; };
    IMCloudKitACAccountRepairMigrationVersion = 1;
    IMCloudKitAccountStatusKey = 4;
    IMCloudKitAnalyticSyncDatesDictionary = { CloudKitAttachmentDownloadCompletedDate = 1734237662.266129; CloudKitAttachmentDownloadCompletedDateProductBuildVersion = "24B2083"; CloudKitAttachmentDownloadFirstCompletedDate = 1734237662.266129; CloudKitAttachmentDownloadFirstCompletedDateProductBuildVersion = "24B2083"; CloudKitAttachmentDownloadStartDate = 1734237662.15761; CloudKitAttachmentDownloadStartDateProductBuildVersion = "24B2083"; CloudKitFirstRestoreAttemptedDate = 1734237652.634519; CloudKitFirstRestoreAttemptedDateProductBuildVersion = "24B2083"; CloudKitFirstRestoreCompletedDate = 1734237659.60753; CloudKitFirstRestoreCompletedDateProductBuildVersion = "24B2083"; CloudKitFullSyncAttemptedDate = 1734574313.46702; CloudKitFullSyncAttemptedDateProductBuildVersion = "24B2083"; CloudKitFullSyncCompletedDate = 1734574323.22971; CloudKitFullSyncCompletedDateProductBuildVersion = "24B2083"; CloudKitFullSyncFirstCompletedDate = 1734237660.9317942; CloudKitFullSyncFirstCompletedDateProductBuildVersion = "24B2083"; CloudKitInitialStartDate = 1733984610.351519; CloudKitInitialStartDateProductBuildVersion = "24B2083"; CloudKitInitialSyncCompletedDate = 1733984622.8658462; CloudKitInitialSyncCompletedDateProductBuildVersion = "24B2083"; CloudKitInitialSyncFirstCompletedDate = 1733984622.8658462; CloudKitInitialSyncFirstCompletedDateProductBuildVersion = "24B2083"; CloudKitSyncDate = 1734574323.22971; CloudKitSyncDateProductBuildVersion = "24B2083"; };
    IMCloudKitStartingDisableDevices = false;
    IMCloudKitStartingEnabledSettingChange = false;
    IMCloudKitStartingInitialSync = false;
    IMCloudKitStartingPeriodicSync = false;
    IMCloudKitSyncCancelled = false;
    IMCloudKitSyncControllerSyncRecordTypeKey = 0;
    IMCloudKitSyncControllerSyncStateKey = 0;
    IMCloudKitSyncControllerSyncTypeKey = 0;
    IMCloudKitSyncJobStateKey = 0;
    IMCloudKitSyncPaused = false;
    IMCloudKitSyncStatusKey = 0;
    IMCloudKitSyncTypeKey = 2;
    LocalDBStats = { allSynced = 176; attStats = { total = 0; }; chatStats = { Status 1 = 22; total = 22; }; deletedAttachments = 0; deletedChats = 0; deletedMessages = 0; deletedRecoverableMessages = 0; msgStats = { Status 1 = 154; total = 154; }; syncedAttachments = 0; syncedChats = 22; syncedMessages = 154; syncedRecoverableMessages = 0; totalAttachments = 0; totalChats = 22; totalCount = 176; totalMessages = 154; totalRecoverableMessages = 0; unresolvedAttachments = 0; unresolvedChats = 0; unresolvedCount = 0; unresolvedMessages = 0; unresolvedRecoverableMessages = 0; updateT1NeedingSync = 0; updateT2NeedingSync = 0; };
    MiCDeviceIdentifier = "7E3D23D1-39CC-4B62-AC8F-47331F43AA47";
    Server.TotalRecords.chatManateeZone = 22;
    Server.TotalRecords.messageManateeZone = 154;
    Server.TotalRecords.recoverableMessageDeleteZone = 4;
    enableCKSyncingV2 = true;
    hadPriorPrefs = false;
    hasEnabledMiCByDefault = 1;
    initialSyncRecordHasBeenWritten = true;
    markAttachmentsAsDirtyV6 = true;
    markChatsAsDirtyV4 = true;
    markMessagesAsDirtyV4 = true;
    oneTimeMOCAccountCheckV2 = true;
  };
}