{
  "com.apple.SetupAssistant" = {
    DidSeeAccessibility = true;
    DidSeeActivationLock = false;
    DidSeeAppStore = false;
    DidSeeAppearanceSetup = true;
    DidSeeApplePaySetup = true;
    DidSeeCloudSetup = true;
    DidSeeIntelligence = false;
    DidSeeLockdownMode = false;
    DidSeePrivacy = true;
    DidSeeScreenTime = true;
    DidSeeSiriSetup = true;
    DidSeeSyncSetup = true;
    DidSeeSyncSetup2 = true;
    DidSeeTermsOfAddress = false;
    DidSeeTouchIDSetup = true;
    DidSeeiCloudLoginForStorageServices = true;
    FDECSLVUUIDs = [ "A7617C1B-325A-4167-80C7-968FBFA7F31B"; ];
    InitialAccountOnMac = true;
    InitialAccountSetupDate = "2024-12-12 06:23:01";
    InitialSetupBuildVersion = "24B2083";
    InitialSetupProductVersion = "15.1";
    LastPrivacyBundleVersion = "2";
    LastSeenBuddyBuildVersion = "24B2083";
    LastSeenCloudProductVersion = "15.1";
    LastSeenDiagnosticsProductVersion = "15.1";
    LastSeenSiriProductVersion = "15.1";
    LastSeenSyncProductVersion = "15.1";
    MiniBuddyLaunchReason = 0;
    MiniBuddyLaunchedPostMigration = false;
    MiniBuddyShouldLaunchToResumeSetup = false;
    PreviousBuildVersion = "0";
    PreviousSystemVersion = "0";
    SkipExpressSettingsUpdating = false;
    SkipFirstLoginOptimization = false;
    selectedFDEEscrowType = "iCloudEscrow";
  };
}