#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Create branch and auto switch to it
##?
##? Usage:
##?   branch-create <branch_name>
docs::parse "$@"

if (! git::branch_exists $branch_name); then
	git switch $branch_name
else
	git branch $branch_name
	git switch $branch_name
fi
