#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"
source "$DOTFILES_PATH/shell/aliases.sh"
source "$DOTFILES_TEMPLATE/scripts/git/utils/stash-get.sh"

##? Drop selected stash
##?
##? Usage:
##?   stash-drop
docs::parse "$@"

git stash drop "$(get_stash)"
